all:
  hosts:
    web1:
      ansible_host: 10.0.2.15
      ansible_user: cliente2
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "/home/david/Escritorio/prueba ansible/id_rsa_deploy"